version: "3.9"

services:
  postgres:
    image: postgres:16
    container_name: my_postgres
    restart: always
    env_file:
      - ./backend/.env
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data

  pgadmin:
    image: dpage/pgadmin4
    container_name: pgadmin4_container
    restart: always
    ports:
      - "5050:80"
    env_file:
      - ./backend/.env
    depends_on:
      - postgres

  backend:
    build: ./backend
    container_name: spring_backend
    restart: always
    env_file:
    - ./backend/.env
    environment:
      SPRING_DATASOURCE_URL: jdbc:postgresql://postgres:5432/${POSTGRES_DB}
      SPRING_DATASOURCE_USERNAME: ${POSTGRES_USER}
      SPRING_DATASOURCE_PASSWORD: ${POSTGRES_PASSWORD}
    ports:
      - "8080:8080"
    depends_on:
      - postgres

  webapp:
    build: ./webapp
    container_name: next_webapp
    restart: always
    env_file:
      - ./webapp/.env
    environment:
      NEXT_PUBLIC_BACKEND_URL: http://backend:8080
    ports:
      - "3000:3000"
    depends_on:
      - backend

volumes:
  postgres_data:
